### ISSUE TITLE
ESWD16 Dimmer Switch not found when adding devices

### ISSUE THREAD

**Issue by naclnew** [mozilla-iot/etekcity-adapter#5]
I recently added an Etekcity dimmer switch to my webthings.  My Etekcity switch and outlets are working fine, but it cannot find the new dimmer switch.  The log shows the error:  020-03-08 12:46:59.882 ERROR  : etekcity-adapter: 2020-03-08 12:46:59,880 - WARNING - Unknown device ESWD16.
I understand that not all devices are supported, but wondered if / how this device could be added.  I'm new to the github community, so I don't know if I am expected or encouraged to attempt this myself.  Any help and guidance you can provide is appreciated.

**Comment by mrstegeman** [comment]
I just release v0.5.0 of this add-on, which will hopefully fix your issue. Let me know if it doesn't work, for some reason.

**Comment by naclnew** [comment]
It is working perfectly!  Thanks for the quick response!
